# Generated by Django 4.1.3 on 2022-11-27 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listing_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=255)),
                ('listing', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commentItem', to='auctions.listing')),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='commentingUser', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
