# Generated by Django 4.1.4 on 2023-01-18 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_comment_user_followers_post_comment_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='user',
            name='comments',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
