# Generated by Django 4.1.4 on 2023-02-05 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_post_updated_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_timestamp',
        ),
    ]
